package com.cosmicocean.integration

import android.content.Context
import android.content.SharedPreferences
import android.graphics.Bitmap
import android.graphics.Color
import com.cosmicocean.data.StarEntity
import com.cosmicocean.utils.WallpaperPreferencesManager
import com.cosmicocean.wallpaper.LocalWallpaperGenerator
import com.cosmicocean.wallpaper.WallpaperTheme
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.Mock
import org.mockito.Mockito.*
import org.mockito.MockitoAnnotations
import org.mockito.junit.MockitoJUnitRunner
import java.io.File

/**
 * End-to-End tests for custom wallpaper functionality.
 *
 * These tests verify the complete flow:
 * 1. User selects custom wallpaper image
 * 2. Image is saved to local storage
 * 3. Wallpaper mode is set to "custom"
 * 4. Wallpaper path is stored in preferences
 * 5. RealTimeWallpaperService reads preferences correctly
 * 6. LocalWallpaperGenerator renders custom background with tasks
 */
@RunWith(MockitoJUnitRunner.Silent::class)
class CustomWallpaperE2ETest {

    @Mock
    private lateinit var mockContext: Context

    @Mock
    private lateinit var mockSharedPreferences: SharedPreferences

    @Mock
    private lateinit var mockEditor: SharedPreferences.Editor

    private lateinit var prefsManager: WallpaperPreferencesManager

    // Test data
    private val testTasks = listOf(
        StarEntity(
            id = "task1",
            title = "Test Task 1",
            urgency = 2,
            dueDate = System.currentTimeMillis() + 3600000, // 1 hour from now
            x = 100f,
            y = 100f,
            isCompleted = false,
            isArchived = false,
            isDeleted = false
        ),
        StarEntity(
            id = "task2",
            title = "Test Task 2",
            urgency = 3,
            dueDate = System.currentTimeMillis() + 7200000, // 2 hours from now
            x = 200f,
            y = 200f,
            isCompleted = false,
            isArchived = false,
            isDeleted = false
        )
    )

    @Before
    fun setup() {
        MockitoAnnotations.openMocks(this)

        // Setup SharedPreferences mock
        `when`(mockContext.getSharedPreferences("wallpaper_prefs", Context.MODE_PRIVATE))
            .thenReturn(mockSharedPreferences)
        `when`(mockSharedPreferences.edit()).thenReturn(mockEditor)
        `when`(mockEditor.putString(anyString(), anyString())).thenReturn(mockEditor)
        `when`(mockEditor.putBoolean(anyString(), anyBoolean())).thenReturn(mockEditor)
        `when`(mockEditor.remove(anyString())).thenReturn(mockEditor)
        `when`(mockEditor.commit()).thenReturn(true)

        prefsManager = WallpaperPreferencesManager(mockContext)
    }

    // ==================== PREFERENCE TESTS ====================

    @Test
    fun `setWallpaperMode to CUSTOM should store correct value`() {
        val result = prefsManager.setWallpaperMode(WallpaperPreferencesManager.WALLPAPER_MODE_CUSTOM)

        assertTrue("setWallpaperMode should return true for valid mode", result)
        verify(mockEditor).putString("wallpaper_mode", "custom")
        verify(mockEditor).commit()
    }

    @Test
    fun `setWallpaperMode to GENERATED should store correct value`() {
        val result = prefsManager.setWallpaperMode(WallpaperPreferencesManager.WALLPAPER_MODE_GENERATED)

        assertTrue("setWallpaperMode should return true for valid mode", result)
        verify(mockEditor).putString("wallpaper_mode", "generated")
        verify(mockEditor).commit()
    }

    @Test
    fun `setWallpaperMode with invalid value should return false`() {
        val result = prefsManager.setWallpaperMode("invalid")

        assertFalse("setWallpaperMode should return false for invalid mode", result)
        verify(mockEditor, never()).putString(eq("wallpaper_mode"), anyString())
    }

    @Test
    fun `getWallpaperMode should return GENERATED by default`() {
        `when`(mockSharedPreferences.getString("wallpaper_mode", "generated"))
            .thenReturn("generated")

        val mode = prefsManager.getWallpaperMode()

        assertEquals("Default mode should be 'generated'", "generated", mode)
    }

    @Test
    fun `getWallpaperMode should return CUSTOM when set`() {
        `when`(mockSharedPreferences.getString("wallpaper_mode", "generated"))
            .thenReturn("custom")

        val mode = prefsManager.getWallpaperMode()

        assertEquals("Mode should be 'custom' when set", "custom", mode)
    }

    @Test
    fun `setCustomWallpaperPath should store file path`() {
        val testPath = "/data/data/com.cosmicocean/files/custom_wallpaper.jpg"

        val result = prefsManager.setCustomWallpaperPath(testPath)

        assertTrue("setCustomWallpaperPath should return true", result)
        verify(mockEditor).putString("custom_wallpaper_path", testPath)
        verify(mockEditor).commit()
    }

    @Test
    fun `setCustomWallpaperPath with null should remove the path`() {
        val result = prefsManager.setCustomWallpaperPath(null)

        assertTrue("setCustomWallpaperPath(null) should return true", result)
        verify(mockEditor).remove("custom_wallpaper_path")
        verify(mockEditor).commit()
    }

    @Test
    fun `getCustomWallpaperPath should return null by default`() {
        `when`(mockSharedPreferences.getString("custom_wallpaper_path", null))
            .thenReturn(null)

        val path = prefsManager.getCustomWallpaperPath()

        assertNull("Default custom path should be null", path)
    }

    @Test
    fun `getCustomWallpaperPath should return stored path when set`() {
        val testPath = "/data/data/com.cosmicocean/files/custom_wallpaper.jpg"
        `when`(mockSharedPreferences.getString("custom_wallpaper_path", null))
            .thenReturn(testPath)

        val path = prefsManager.getCustomWallpaperPath()

        assertEquals("Path should match stored value", testPath, path)
    }

    // ==================== BITMAP GENERATION TESTS ====================

    @Test
    fun `generateWithCustomBackground should create bitmap with correct dimensions`() {
        val width = 1080
        val height = 2400
        val customBackground = createTestBitmap(width, height, Color.BLUE)

        val result = LocalWallpaperGenerator.generateWithCustomBackground(
            tasks = testTasks,
            totalTaskCount = testTasks.size,
            customBackground = customBackground,
            width = width,
            height = height
        )

        assertNotNull("Result bitmap should not be null", result)
        assertEquals("Width should match", width, result.width)
        assertEquals("Height should match", height, result.height)
        assertEquals("Config should be ARGB_8888", Bitmap.Config.ARGB_8888, result.config)

        // Clean up
        customBackground.recycle()
        result.recycle()
    }

    @Test
    fun `generateWithCustomBackground should preserve custom background color`() {
        val width = 100
        val height = 100
        val testColor = Color.RED
        val customBackground = createTestBitmap(width, height, testColor)

        val result = LocalWallpaperGenerator.generateWithCustomBackground(
            tasks = emptyList(), // No tasks to interfere with background
            totalTaskCount = 0,
            customBackground = customBackground,
            width = width,
            height = height
        )

        // Check corner pixel (should be custom background color, not default)
        val cornerPixel = result.getPixel(0, 0)

        // The corner should have some color from the background (not transparent)
        val alpha = Color.alpha(cornerPixel)
        assertTrue("Background should not be fully transparent", alpha > 0)

        // Clean up
        customBackground.recycle()
        result.recycle()
    }

    @Test
    fun `generateWithCustomBackground should work with different aspect ratios`() {
        val testCases = listOf(
            Pair(1080, 1920),  // 9:16 portrait
            Pair(1080, 2400),  // Taller portrait
            Pair(1440, 3120),  // High-res portrait
            Pair(720, 1280),   // Lower-res portrait
        )

        testCases.forEach { (width, height) ->
            val customBackground = createTestBitmap(100, 100, Color.GREEN) // Small source

            val result = LocalWallpaperGenerator.generateWithCustomBackground(
                tasks = testTasks,
                totalTaskCount = testTasks.size,
                customBackground = customBackground,
                width = width,
                height = height
            )

            assertNotNull("Result should not be null for ${width}x${height}", result)
            assertEquals("Width should match for ${width}x${height}", width, result.width)
            assertEquals("Height should match for ${width}x${height}", height, result.height)

            customBackground.recycle()
            result.recycle()
        }
    }

    @Test
    fun `generateWithCustomBackground should not crash with recycled bitmap`() {
        val customBackground = createTestBitmap(100, 100, Color.BLUE)
        customBackground.recycle() // Intentionally recycle

        // This should throw or handle gracefully
        try {
            LocalWallpaperGenerator.generateWithCustomBackground(
                tasks = testTasks,
                totalTaskCount = testTasks.size,
                customBackground = customBackground,
                width = 1080,
                height = 2400
            )
            // If we get here without exception, the code handled it gracefully
        } catch (e: Exception) {
            // Expected - recycled bitmap should cause an exception
            assertTrue("Should throw IllegalStateException for recycled bitmap",
                e is IllegalStateException || e is IllegalArgumentException)
        }
    }

    @Test
    fun `generate (themed) should create valid bitmap`() {
        val width = 1080
        val height = 2400

        val result = LocalWallpaperGenerator.generate(
            tasks = testTasks,
            totalTaskCount = testTasks.size,
            theme = WallpaperTheme.COSMIC,
            width = width,
            height = height
        )

        assertNotNull("Themed wallpaper should not be null", result)
        assertEquals("Width should match", width, result.width)
        assertEquals("Height should match", height, result.height)

        result.recycle()
    }

    @Test
    fun `generate should work with no tasks (clear state)`() {
        val width = 1080
        val height = 2400

        val result = LocalWallpaperGenerator.generate(
            tasks = emptyList(),
            totalTaskCount = 0,
            theme = WallpaperTheme.OCEAN,
            width = width,
            height = height
        )

        assertNotNull("Clear state wallpaper should not be null", result)
        assertEquals("Width should match", width, result.width)
        assertEquals("Height should match", height, result.height)

        result.recycle()
    }

    // ==================== FLOW VERIFICATION TESTS ====================

    @Test
    fun `custom wallpaper flow - complete scenario`() {
        // Simulate the complete flow
        val testPath = "/data/data/com.cosmicocean/files/custom_wallpaper.jpg"

        // Step 1: Set wallpaper mode to custom
        val modeResult = prefsManager.setWallpaperMode(WallpaperPreferencesManager.WALLPAPER_MODE_CUSTOM)
        assertTrue("Setting mode to custom should succeed", modeResult)

        // Step 2: Set custom wallpaper path
        val pathResult = prefsManager.setCustomWallpaperPath(testPath)
        assertTrue("Setting path should succeed", pathResult)

        // Verify both calls were made correctly
        verify(mockEditor).putString("wallpaper_mode", "custom")
        verify(mockEditor).putString("custom_wallpaper_path", testPath)
        verify(mockEditor, times(2)).commit()
    }

    @Test
    fun `switching from custom back to generated should work`() {
        // Start with custom mode
        prefsManager.setWallpaperMode(WallpaperPreferencesManager.WALLPAPER_MODE_CUSTOM)
        prefsManager.setCustomWallpaperPath("/some/path.jpg")

        // Switch back to generated
        val result = prefsManager.setWallpaperMode(WallpaperPreferencesManager.WALLPAPER_MODE_GENERATED)

        assertTrue("Switching to generated should succeed", result)
        verify(mockEditor).putString("wallpaper_mode", "generated")
    }

    // ==================== HELPER METHODS ====================

    private fun createTestBitmap(width: Int, height: Int, color: Int): Bitmap {
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        bitmap.eraseColor(color)
        return bitmap
    }
}
